import Head from 'next/head'
import Image from 'next/image'
import Styles from '@/styles/Index.module.scss'
import NavBar from './components/NavBar'

export default function index() {
  return (
    <>
      <Head>
        <title>Voice For Those Who Can`&apos;`t Speak - NWAO</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <NavBar />
    </>
  )
}
